print("Vamos a descubrir cuándo cumplirás 100 años")
nombre = input("Ingresa tu nombre ")
edad = input("Ingresa tu edad ")
cuando_cumpla_100_años = 2121-int(edad)
print(f"Cumplirás 100 años en {cuando_cumpla_100_años}")
